### ISSUE TITLE
Undeclared variable i

### ISSUE THREAD

**Issue by bjornharrtell** [r-spatial/leafem#19]
https://github.com/r-spatial/leafem/blob/0016ec18b7e4fadf7e8760af280a6e760fa9f214/inst/htmlwidgets/lib/FlatGeoBuf/fgb.js#L132

I can recommend eslint. :)

**Comment by tim-salabim** [comment]
Thanks! that's a classical R thing! I am happy I remembered to start counting from 0 instead of 1 (as is done in R).
Fixed now
