### ISSUE TITLE
Suggest mapdeck but don't import it

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/leafem#20]
I was surprised to find that installing `tmap` also depends on installing `mapdeck`. This is a pretty hefty dependency for what seems to be a relatively low level (and very used and highly handy) package.

It also seems mapdeck is only used in a couple of non mission-critical places: https://github.com/r-spatial/leafem/search?q=mapdeck&unscoped_q=mapdeck

I therefore suggest moving it to a Suggests. Plan to put in a PR doing just that.

Context: trying to reduce build times of geocomputation with R on GH Actions, currently over an hour! https://github.com/Robinlovelace/geocompr/issues/546

**Comment by tim-salabim** [comment]
Thanks Robin, I will take care of this soon

**Comment by Robinlovelace** [comment]
Great, I *think* my PR fixes it but am not 100% sure and you may have other ideas on this.

**Comment by tim-salabim** [comment]
merged now. do you need this on CRAN any time soon?

**Comment by Robinlovelace** [comment]
Sooner the better IMO, no changes to the worse only to the better I think, although build times are now down to less than 10 minutes thanks to caching https://github.com/Robinlovelace/geocompr/actions

**Comment by tim-salabim** [comment]
Ok, I'll try my best... Need to get leafgl to CRAN first and that needs a little cleaning before I can ship it. Exciting times!

**Comment by Robinlovelace** [comment]
OK if you want any testing or other input just ping me. Great to see all this rapid progressive in interactive mapping, amazing work!

**Comment by tim-salabim** [comment]
It's all manageable. Just need to replace all the mapview things in examples etc that I had in there for convenience. I was hoping to release leafgl with a boom, but I guess now is as good a time as any
