### ISSUE TITLE
OnMouseOut returns error

### ISSUE THREAD

**Issue by fpirotti** [r-spatial/leafem#23]
Hi thanks for the nice tool! Can you please add a line
if( strip !==null) strip.remove(); 
(see image below)  To avoid error if the DOM element is not present? Thanks
![immagine](https://user-images.githubusercontent.com/1391292/86397096-7bbe9480-bca3-11ea-9805-dda294af8de0.png)

**Comment by tim-salabim** [comment]
Thanks, should be fixed now!
