### ISSUE TITLE
Can't get setview() to work in shiny app, with raster added using addGeoRaster

### ISSUE THREAD

**Issue by DFletcher-UK** [r-spatial/leafem#35]
My aim is to make a shiny app with a map displaying raster data, which can be updated by the user, using sliders (or similar) to input the parameters for changing the raster. I want the changes to take effect when an "update" button is pressed, rather than when the slider is moved. In practical use, the user may be zoomed on a particular location when they wish to make a change and update the map. When I run the below app and click to update the map, the map always zooms back out to show the full extent of the raster. I was under the impression that using the leafletProxy() command would leave the zoom etc., intact, however that doesn't seem to happen. In this code, I have tried to save the viewing parameters of the map, then update the raster, then revert to the saved viewing params, however it still zooms out. Is there a  way to get setview() to work in this context, please?

Reprex:

library(stars)
library(leaflet)
library(viridis)
library(RColorBrewer)
library(scales)
library(lattice)
library(raster)
library(rgdal)
library(leafem)
library(shiny)
library(shinyjs)

x<-raster(res=0.0006, xmn=1.153975, xmx=3.663575, ymn=47.84775, ymx=49.49975)
values(x)[]<-rnorm(length(values(x)), 50)

ui <- fluidPage(
 
  titlePanel("Tabsets"),
 
  sidebarLayout(
    
    sidebarPanel(
      
      br(),
      
      sliderInput("n1",
                  "Slider1",
                  value = 0.1,
                  min = 0,
                  max = 1),
      
      br(),
      actionButton("B1", "Update Map")
      
    ),
    
    mainPanel(
      
      tabsetPanel(type = "tabs",
                  tabPanel("My Interactive map1's name",
                           div(class="outer",
                              
                               leafletOutput("map", width=800, height=800)
                           ))
      )
      
    )
  )
)

server <- function(input, output, session) {
  
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      leafem:::addGeoRaster(x,                   
                            group = "My_raster",
                            layerId = NULL,
                            resolution = 96,
                            opacity = 0.7,
                            zoom = 10,
                            colorOptions = leafem:::colorOptions(
                              palette = inferno, 
                              breaks = seq(x@data@min, x@data@max, 0.5),
                              na.color = "transparent"
                            )
      ) %>%
      
      addLegend(pal=colorNumeric(inferno(256), values(x),
                                 na.color = "transparent"), values = values(x), title = "My_raster", position = "bottomleft")%>%
      addLayersControl(overlayGroups = c("My_raster")) %>%
      setView(lng = 2.35, lat = 48.86, zoom = 10)
      })
  
   observeEvent(input$B1,{  ### run this sub-routine when the button, "B1", is clicked
    
    x<-x*input$n1 ### Update the raster (do anything using slider inputs) before the plotting
    savedZoom<-input$map_zoom
    savedBounds<-input$map_bounds
    savedCenter<-input$map_center
    
    leafletProxy("map") %>% ### meant to update the map, without altering anything else, e.g. zoom, etc.
      
      leafem:::addGeoRaster(x,                   
                            group = "My_raster",
                            layerId = NULL,
                            resolution = 96,
                            opacity = 0.7,
                            colorOptions = leafem:::colorOptions(
                              palette = inferno, 
                              breaks = seq(x@data@min, x@data@max, 0.5),
                              na.color = "transparent"
                            )
      )%>%
      
      clearControls()%>%
      addLegend(pal=colorNumeric(inferno(256), values(x),
                                 na.color = "transparent"), values = values(x), title = "My_raster", position = "bottomleft")%>%
      leaflet::setView(lng=savedCenter$lng, lat=savedCenter$lat, zoom=savedZoom) # This should make the map view revert to saved params
  })
  
}

shinyApp(ui=ui,server=server)

**Comment by trafficonese** [comment]
Whenever a Georaster/Geotiff is added to the map, this line is executed last. That's why the the map bounces back to the full extent.

https://github.com/r-spatial/leafem/blob/b90a32e5eab5ee8e274f7fdde37d475e02a50a5c/inst/htmlwidgets/lib/georaster-for-leaflet/georaster-binding.js#L125

One workaround would be to call `setView` with a `shinyjs::delay` like:
```
    shinyjs::delay(2000,
                     leaflet::setView(leafletProxy("map"), 
                                      lng=savedCenter$lng, lat=savedCenter$lat, zoom=savedZoom) 
      )
```

However, this will zoom to full extent first and then reset the previous view and might not work if the delay is too short.

**Comment by tim-salabim** [comment]
Thanks @trafficonese for identifying the culprit. We could easily just add an `autozoom` argument to `addGeoRaster` and condition the above line on it. Default would be `TRUE` of course, but that way users can get more control... What do you think?

**Comment by DFletcher-UK** [comment]
> Whenever a Georaster/Geotiff is added to the map, this line is executed last. That's why the the map bounces back to the full extent.
> 
> https://github.com/r-spatial/leafem/blob/b90a32e5eab5ee8e274f7fdde37d475e02a50a5c/inst/htmlwidgets/lib/georaster-for-leaflet/georaster-binding.js#L125
> 
> One workaround would be to call `setView` with a `shinyjs::delay` like:
> 
> ```
>     shinyjs::delay(2000,
>                      leaflet::setView(leafletProxy("map"), 
>                                       lng=savedCenter$lng, lat=savedCenter$lat, zoom=savedZoom) 
>       )
> ```
> 
> However, this will zoom to full extent first and then reset the previous view and might not work if the delay is too short.

Thanks, @trafficonese . Did that work for you? It was one of the first things I tried, as I assumed perhaps it was still finishing an operation. I tried with a few different delays and couldn't get it to work.

**Comment by trafficonese** [comment]
Yes, I agree @tim-salabim. That would be the nicer solution!

**Comment by DFletcher-UK** [comment]
> Thanks @trafficonese for identifying the culprit. We could easily just add an `autozoom` argument to `addGeoRaster` and condition the above line on it. Default would be `TRUE` of course, but that way users can get more control... What do you think?

@tim-salabim That sounds awesome! If you have the time, that would be great. Thanks!

**Comment by tim-salabim** [comment]
Thanks to @trafficonese this should work now by setting `autozoom = FALSE`. @DFletcher-UK could you pls re-try and let us know?

**Comment by DFletcher-UK** [comment]
> Thanks to @trafficonese this should work now by setting `autozoom = FALSE`. @DFletcher-UK could you pls re-try and let us know?

@tim-salabim & @trafficonese  - It works perfectly - AWESOME! Thanks so much. :)

**Comment by dewalex** [comment]
@DFletcher-UK @trafficonese 
I cannot get the autozoom=FALSE to work.  I am using the 0.1.3 version.  Did you have to update something to make it work?

**Comment by trafficonese** [comment]
I think you still have to install the github version - `remotes::install_github("r-spatial/leafem")`

**Comment by dewalex** [comment]
@trafficonese Thank you!  For whatever reason, I was thinking that the changes had already been pushed to CRAN.
