### ISSUE TITLE
addGeoRaster autozoom will not set to FALSE

### ISSUE THREAD

**Issue by dewalex** [r-spatial/leafem#37]
I have a Shiny app with a list of rasters that plot to leaflet map on a loop, when I do 
```
                 for(i in 1:length(rastit)){

                      leafletProxy("map") %>% 
                       leafem::addGeoRaster(rastit[[i]], opacity=0.8,layerId = paste0("ras", i), 
                           colorOptions = colorOptions(palette=colores, breaks=breaks, na.color = "transparent"),
                               options=tileOptions(updateWhenZooming = FALSE), group="BioVolume", autozoom=FALSE) 
                            }

```

the map still autozooms to the last plotted raster.  Even if I ```fitBounds()``` after each call, it will still end up overriding that and zooming to the raster.  

Any solution or workaround for this?

@tim-salabim

**Comment by tim-salabim** [comment]
It is not easy to know what is going on without a minimal
reproducible example, especially when dealing with shiny. Can you at all
provide a reprex with some built in data set?

**Comment by dewalex** [comment]
No problem.  We can just add ```fitBounds()``` to the package example.

See the difference between when we are trying to fitBounds after adding a geoRaster:
```
if (interactive()) {
    library(leaflet)
    library(leafem)
    library(stars)
    
    tif = system.file("tif/L7_ETMs.tif", package = "stars")
    x1 = read_stars(tif)
    x1 = x1[, , , 3] # band 3
    
    leaflet() %>%
        addTiles() %>%
        leafem:::addGeoRaster(
            x1
            , opacity = 1
            , colorOptions = colorOptions(
                palette = grey.colors(256)
            ), 
             autozoom=FALSE
        ) %>% 
         fitBounds(-35, -7, -32, -10)  #this should give a more zoomed out view
}
```
and fitting those bounds without adding a geoRaster:
```
leaflet() %>%
     addTiles() %>%
         fitBounds(-35, -7, -32, -10)
```
@tim-salabim , sorry forgot to @ you when I replied.

**Comment by tim-salabim** [comment]
Hi @dewalex can you please retry with the current version? It works for me

**Comment by dewalex** [comment]
@tim-salabim Sorry about that, for whatever reason, I thought the changes had already been pushed to CRAN.  I downloaded the github version as suggested in the other thread and it works perfectly.
