### ISSUE TITLE
Not specifying opacity and/or colorOptions leads to error

### ISSUE THREAD

**Issue by frousseu** [r-spatial/leafem#39]
Hello!

An error occurs if argument `colorOptions` is not given when `opacity` is. Here is an example from the help file:

```r
 library(leaflet)
 library(leafem)
 library(stars)

  tif = system.file("tif/L7_ETMs.tif", package = "stars")
  x1 = read_stars(tif)
  x1 = x1[, , , 3] # band 3

  leaflet() %>%
    addTiles() %>%
    leafem:::addGeoRaster(
      x1
      , opacity = 1
    )

##   Error in evalAll(list) : 
##    promise already under evaluation: recursive default argument reference or earlier problems?
```

The same error arises if both `opacity` and `colorOptions` are not specified. This is with R 4.0.4 and leafem 0.1.3 on Windows.

Thanks!

**Comment by frousseu** [comment]
I should add that only specifying `colorOptions` and not `opacity` does not lead to an error.

**Comment by tim-salabim** [comment]
Can you please try with `remotes::install_github("r-spatial/leafem")`?

**Comment by frousseu** [comment]
With the GitHub version it works
