### ISSUE TITLE
Installing leafem fails in R 3.6.1 with RStudio

### ISSUE THREAD

**Issue by jmoehlen** [r-spatial/leafem#41]
### Installation Error in R 3.6.1

Trying to install the `leafem` package with `R 3.6.1` using `RStudio Version 1.1.456` with Anaconda 3 results in the following **installation error**:

`ERROR: lazy loading failed for package 'leafem'`
`* removing 'path/Anaconda3/envs/rstudio/lib/R/library/leafem'`
`Warning in install.packages :`
`  installation of package ‘leafem’ had non-zero exit status`

### NO Installation Error in R 3.6.1

This behaviour **does not occur** in `R version 3.6.3 (2020-02-29)` using RGui.

### The full command and its output:

I'm sorry, some of the output is in German, I hope the issue is clear nonetheless.

`> install.packages("leafem")`

  `There is a binary version available but the source version is later:`
  `    binary source needs_compilation`
`leafem  0.1.3  0.1.6             FALSE`

`installing the source package ‘leafem’`

`trying URL 'https://cran.rstudio.com/src/contrib/leafem_0.1.6.tar.gz'`
`Content type 'application/x-gzip' length 3203539 bytes (3.1 MB)`
`downloaded 3.1 MB`

`"path\user\Documents"`
`CMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.`
`UNC-Pfade werden nicht unterstützt.`
`Stattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.`
`* installing *source* package 'leafem' ...`
`** Paket 'leafem' erfolgreich entpackt und MD5 Summen überprüft`
`** using staged installation`
`** R`
`** inst`
`** byte-compile and prepare package for lazy loading`
`ERROR: lazy loading failed for package 'leafem'`
`* removing 'path/Anaconda3/envs/rstudio/lib/R/library/leafem'`
`Warning in install.packages :`
`  installation of package ‘leafem’ had non-zero exit status`

`The downloaded source packages are in`
`	‘path\user\AppData\Local\Temp\Rtmpys7GRL\downloaded_packages’`

**Comment by tim-salabim** [comment]
What happens if you install the binary instead of the source version?

**Comment by jmoehlen** [comment]
> 
> 
> What happens if you install the binary instead of the source version?

@tim-salabim How do I do that? 🙈

**Comment by tim-salabim** [comment]
You seem to say/type 'yes' when R(Studio) asks you if you want to install the source (newer) version. Can you try saying 'no'?

**Comment by tim-salabim** [comment]
Also, have you considered updating R? We're at 4.1.0 now...

**Comment by jmoehlen** [comment]
@tim-salabim The console never waited for a reply during the installation of leafem - so I typed neither "yes" nor "no". After a restart today, RStudio seems to recognise that I have installed a newer version of R (3.6.3) **and** `library(leafem)` works fine, too. So, it seems to be an issue occuring only in older versions of R.

**Comment by tim-salabim** [comment]
So can we close this?

**Comment by jmoehlen** [comment]
@tim-salabim From my point of view, yes we can! Cheers!
