### ISSUE TITLE
mutliple logos using addLogo

### ISSUE THREAD

**Issue by h-a-graham** [r-spatial/leafem#43]
Thanks for the great package! 
This is likely misunderstanding on my part, but I was hoping to add multiple logos for two oranisations to my leaflet map.
I had assumed that something like this would give the desired result...

```
library(leaflet)
library(leafem)

img <- "https://www.r-project.org/logo/Rlogo.svg"

leaflet() %>% 
  addTiles() %>% 
  addLogo(img, url = "https://www.r-project.org/logo/") %>%
  addLogo(img, url = "https://www.r-project.org/logo/", offset.y = 100)
```

However, this only produces one logo. Is there a way to add more?

Cheers,
Hugh

**Comment by tim-salabim** [comment]
I fear this is currently not possible. We need a different implementation of the `addLogo` function to allow for multiple logos. I do have an idea how to achieve this, but am currently a bit stretched for time regarding OS development.

**Comment by h-a-graham** [comment]
Thanks for the super quick reply! No problem at all - I'm sure I can find a compromise for now and will update here with anything useful.
