### ISSUE TITLE
addStaticLabels HTML tags in labels ignored

### ISSUE THREAD

**Issue by hkschr** [r-spatial/leafem#46]
Hi,
I just tried to add labels which extend over multiple lines to a map with `addStaticLabels`. Therefore I added the HTML tag `<br>` to the labels and marked them as HTML via `htmltools::HTML`. However, it did not work out and the full label was added to the map (see second example). I then tested the same approach with the `addLabelOnlyMarkers` function of `leaflet` and it worked. 

``` r
# attach packages
library("sf")
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library("leaflet")
library("leafem")

# attach data
inp = read_sf(system.file("shape/nc.shp", package="sf"))[1:3, ]

# this works when using addLabelOnlyMarkers
xy = st_centroid(inp) %>% st_coordinates() %>% as.data.frame()
#> Warning in st_centroid.sf(inp): st_centroid assumes attributes are constant over
#> geometries of x
xy$label <- paste0("HERE IS <br> ", inp$NAME)

lopts = labelOptions(noHide = TRUE, 
                     direction = 'top', 
                     textOnly = TRUE)
leaflet(inp) %>%
  addProviderTiles("OpenStreetMap") %>%
  addFeatures(.) %>%
  addLabelOnlyMarkers(map = ., lng = xy[["X"]], lat = xy[["Y"]],
                      label = lapply(xy$label, htmltools::HTML),
                      labelOptions = lopts)

```

![](https://i.imgur.com/HuXHHw9.png)

``` r
# ... but does not work when using leafem::addStaticLabels
leaflet(inp) %>%
  addProviderTiles("OpenStreetMap") %>%
  addFeatures(.) %>%
  leafem::addStaticLabels(map = ., 
                          label = lapply(xy$label, htmltools::HTML),
                          labelOptions = lopts)

```
![](https://i.imgur.com/KMrectV.png)

I just have taken a look at the `addStaticLabels` function and the reason why my approach did not work is that the labels are converted to character before they are passed on to the `addLabelOnlyMarkers` function.

``` r
map = leaflet::addLabelOnlyMarkers(map, 
                                   lng = mat[, 1], 
                                   lat = mat[, 2], 
                                   
                                   label = as.character(label), 
                                   
                                   group = group, 
                                   layerId = layerId, 
                                   labelOptions = dots)
```

Is there a reason why the labels have to be converted to character? If the `as.character` would be removed HTML tags could be used to format the labels.

<sup>Created on 2021-10-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jannes-m** [comment]
Here is the offending [line of code](https://github.com/r-spatial/leafem/blob/90c40aa3fc08d13ebf6db815ece2ea5d9ed46d9a/R/labels.R#L150). We can take care of this via a PR of course, but first wanted to ask if there was a specific reason for the `as.character()` statement.

**Comment by tim-salabim** [comment]
Nope, no obvious reason that I can remember. How urgent is this?

**Comment by jannes-m** [comment]
Since we already have a solution, it is not that urgent. It would be just nice if `addStaticLabels()` would work with html code in the next release (see #47).

**Comment by tim-salabim** [comment]
Cool, I'll merge this soon then.

**Comment by tim-salabim** [comment]
PR merged, so this should be resoled now.
