### ISSUE TITLE
Feature request (addLogo): ability to change logo depending on selected baselayer

### ISSUE THREAD

**Issue by jzadra** [r-spatial/leafem#49]
I'd like to have a different logo (or legend) depending on which baselayer is selected. (Is there a way to do this already?).

**Comment by tim-salabim** [comment]
Are you using addLogo to show a legend for the respective baselayers? Or what is the use- case?

**Comment by jzadra** [comment]
My goal is to have a logo (or html control) that includes the layer title so as to make the layer title more prominent and separate from the layers control box.

Something akin to this:
![image](https://user-images.githubusercontent.com/25590353/143938172-4633e6ec-f6d0-4076-89bc-638b0d698293.png)

Where the logo in the top right is dependent on the selected baseGroup

**Comment by tim-salabim** [comment]
I think `leaflet::addControl` would be better suited for this type of thing. How good is your JavaScript knowledge? I think you'd need to attach all images to your map and then have some JS code to select the right one when the baseGroup changes. Not trivial, but doable I think

**Comment by jzadra** [comment]
Thanks, yeah I was using addControl for the image I shared.  Unfortunately my JS knowledge is non-existent :(.  I will ask for help on SO.

**Comment by tim-salabim** [comment]
SO is a good place for this I guess. Could you share the link to your question here, so I can follow. This really is a fun problem.
