### ISSUE TITLE
Rendering Two Different Logos according to Input in Shiny

### ISSUE THREAD

**Issue by amholtz** [r-spatial/leafem#50]
Hello :) 

I am using addlogo from Leafem on a leaflet map. This works as intended in my R function to produce a map with the logo. Let's say a parameter in the function is (ECDC or WHO). If WHO is selected a leaflet map with a WHO logo in the top right hand corner appears. If ECDC is selected a leaflet map with the ECDC logo appears. This works correctly if I run the function in Rstudio. 

If I add this function to my shiny app, along with addlogo, the ability for the function to render new plots according to input is lost. 

Do you have an examples of using addlogo in a shinyapp where an input changes the logo for the leaflet map produced?

Thank you

**Comment by tim-salabim** [comment]
Do you have a reproducible example? It's not easy to understand what exactly you expect.

**Comment by amholtz** [comment]
```
library(shiny)
library(shinyscreenshot)
library(dplyr)

ui <- fluidPage(
  


  titlePanel("Example AddLogo with Leaflet"),
  
  # Sidebar with a slider input for number of bins 
            radioGroupButtons(inputId = "map_format", 
                              label = "Select Map Type", 
                              choices = c("ECDC" = "ECDC",
                                          "WHO" = "WHO"
                              ),
                              selected = 'WHO',
                              direction = "horizontal",
                              justified = TRUE),
            
            # Show a plot of the generated distribution
            mainPanel(
              leafletOutput(("mapsReg_outNew"), height = 700)
          )
)
        
 
  
 
  server <- function(input, output) {
    

    
    output$mapsReg_outNew <- renderLeaflet({
      mapsReg_leaflet(maps_type = "case_rate", map_format = input$map_format, language = 'English')
    }
    )
  }
  
  
  # Run the application 
  shinyApp(ui = ui, server = server)
```

**Comment by amholtz** [comment]
Here is an example, the mapsReg_leaflet function takes maps_type and map_format as parameters and produces the map with the logo. This function works fine. Each time the function is called, a new map is produced with the proper logo.

**Comment by amholtz** [comment]
When the map initially loads with WHO selected. As aspected
![image](https://user-images.githubusercontent.com/17280223/144313753-4e742fd6-331c-4429-9210-9a26887a726f.png)

When you click on ECDC, WHO remains but is darkened:
![image](https://user-images.githubusercontent.com/17280223/144313797-528af5ca-8022-40d8-86e2-f4fd7cb6a7a6.png)

If you go back to WHO, WHO is still there but is now in darkened state
![image](https://user-images.githubusercontent.com/17280223/144313831-b8adb9c9-4db0-4d3d-acc4-508a596b2873.png)

**Comment by tim-salabim** [comment]
Sorry, but that's not a reproducible example... I need to be able to run the code in order to help you. Hence a minimal reproducible example would help very much.
