### ISSUE TITLE
Transparency not working with addGeotiff and colorOptions

### ISSUE THREAD

**Issue by psolymos** [r-spatial/leafem#54]
I am having issues with transparent colors for the `NA` values in the raster (GeoTIFF). I tried different values for `na.color = "transparent"` and all gave the same black result, using CRAN (v 0.1.6) and dev (SHA1 660d9886) being the same in this regard.

```R
library(leaflet)
library(leafem)

leaflet() %>%
        addProviderTiles("Esri.WorldImagery") %>%
        addGeotiff(
          url = "https://peter.solymos.org/testapi/amro1k.tif",
          project = FALSE,
          opacity = 0.8,
          colorOptions = colorOptions(
             palette = hcl.colors(50, palette = "inferno"), 
             domain = c(0, 0.62),
             na.color = "transparent"))
```

<img width="467" alt="Black background around raster" src="https://user-images.githubusercontent.com/831636/158027633-3ce5d16d-28d9-49fe-9d73-ef31edbdb5cd.png">

**Comment by tim-salabim** [comment]
This is a tricky one. 

![image](https://user-images.githubusercontent.com/2826432/158028330-aea40d8b-7775-4089-81f2-d9d200e9a68c.png)

The `georaster.noDataValue` just doesn't quite match the current value being processed (vals), even though it should...

@DanielJDufour any ideas how to catch this? Is there an alternative to checking via `vals === georaster.noDataValue` (whoch is what I'm currently doing - https://github.com/r-spatial/leafem/blob/master/inst/htmlwidgets/lib/georaster-for-leaflet/georaster-binding.js#L108)?

**Comment by tim-salabim** [comment]
This seems to work:

```js
vals.toExponential(7) === georaster.noDataValue.toExponential(7)
```
whereas a value of `8` returns `false`

**Comment by tim-salabim** [comment]
and it seems to fix the issue

![image](https://user-images.githubusercontent.com/2826432/158029047-a8eee723-04a3-4151-b98f-96037a23d56b.png)

**Comment by psolymos** [comment]
Making sure I understand: `georaster.noDataValue` is the value taken from the TIF, and it is not matching with what georaster expects (a numerical thing when evaluating?). Should `noDataValue` be set when saving the TIF?

**Comment by tim-salabim** [comment]
Yes, correct. Can you set the `noDataValue` when saving the `.tif`?

**Comment by psolymos** [comment]
`raster::NAvalue()` lets you to set the `NA` value in R, but that does not affect how the TIF gets written by `raster::writeRaster()`. The `NA` values is `-Inf`. If I set it to `-9999`, save, and read the file back in I still get `-Inf` which is what drives the numerical issue described above.

However, I can save it as a {stars} object with `write_stars(st_as_stars(r), "amro1k-stars.tif")` and that solves this issue:

```R
leaflet() %>%
        addProviderTiles("Esri.WorldImagery") %>%
        addGeotiff(
          url = "https://peter.solymos.org/testapi/amro1k-stars.tif",
          project = FALSE,
          opacity = 0.8,
          colorOptions = colorOptions(
             palette = hcl.colors(50, palette = "inferno"), 
             domain = c(0, 0.62),
             na.color = "transparent"))
```

<img width="1219" alt="Fixed" src="https://user-images.githubusercontent.com/831636/158030371-135184c2-9e28-494c-816b-9c0214351d5f.png">

Thanks for the help!
