### ISSUE TITLE
addLocalFile fails (on GDAL3/PROJ6)

### ISSUE THREAD

**Issue by lbusett** [r-spatial/leafem#6]
On a recently updated system with GDAL3/PROJ6, this currently fails: 

``` r
destfile = tempfile(fileext = ".gpkg")

st_write(st_as_sf(gadmCHE), dsn = destfile)

leaflet() %>%
  addTiles() %>%
  leafem::addLocalFile(destfile)
``` 
with: 

``` r
Error in CPL_proj_is_valid(p4s) : 
  Expecting a single string value: [type=character; extent=3].
In addition: Warning message:
In if (is.na(x)) NA_crs_ else if (inherits(x, "crs")) x else if (is.numeric(x)) CPL_crs_from_epsg(as.integer(x)) else if (is.character(x)) { :
 
 Error in CPL_proj_is_valid(p4s) : 
  Expecting a single string value: [type=character; extent=3]. 
```
, because: 

``` r
prj = gdalUtils::gdalsrsinfo(file, o = "proj4")
``` 

gives:

```r 
 prj
[1] ""                                    "+proj=longlat +datum=WGS84 +no_defs"
[3] ""  
```

This could be solved substituting:

``` r 
prj = gdalUtils::gdalsrsinfo(file, o = "proj4") 
``` 

with, for example, 

``` r
 prj = sp::CRS(rgdal::ogrInfo(file)$p4s)
```

Although this would require adding `rgdal` as an import, I think it would also allow to more easily introduce  PROJ6 workflows based on WKT strings (https://github.com/r-spatial/discuss/issues/28)

**Comment by tim-salabim** [comment]
@lbusett thanks for testing this under GDAL3/PROJ6! Very much appreciated!

Wouldn't something like

```r 
prj = prj[grep("+proj=", prj)]
```

be enough though?

**Comment by tim-salabim** [comment]
@lbusett  I just pushed the (my) proposed change. Could you please re-test on GDAL3/PROJ6 to see if it solves the issue?

**Comment by lbusett** [comment]
Yeah, I guess that should work and is much simpler - I'll test tomorrow on Linux.
 I thought that it would not work on both PROJ4 and PROJ6, so I was proposing the rgdal solution, also because that would give access to the WKT strings needed for PROJ6 reprojection workflows. However, I now noticed that, since reprojection here is based on system calls to ogr2ogr, that would not probably be needed.

**Comment by lbusett** [comment]
@tim-salabim 

tested now: I confirm this works also on GDAL3/PROJ6. CLosing here.

**Comment by lbusett** [comment]
@tim-salabim 

heads-up for this, potentially giving problems for the use of `ogr2ogr` on windows machines  with GDAL 3:

https://github.com/r-spatial/discuss/issues/31

**Comment by tim-salabim** [comment]
@lbusett thanks for the heads-up!
