### ISSUE TITLE
addCOG does not show the layer

### ISSUE THREAD

**Issue by Pakillo** [r-spatial/leafem#61]
Hi

Thanks for the package, so useful!

I'm struggling to map COG (Cloud Optimised Geotiff) layers using leafem::addCOG. The function example works for me, but I can't get my own COG rasters to be shown. Is there any trick on how to prepare them? 

For example, this online COG (https://frodriguezsanchez.net/img/prueba.tif) passes the validation [here](https://mykolakozyr-cogvalidator-appapp-jnzry7.streamlitapp.com/) and can be mapped nicely e.g. in [https://cogeo.org/map](https://www.cogeo.org/map) (see [here](https://www.cogeo.org/map/#/url/https%3A%2F%2Ffrodriguezsanchez.net%2Fimg%2Fprueba.tif/center/91.543,73.396/zoom/8)). But I can't get it to be shown in R:

``` r
library(leaflet)
library(leafem)

leaflet() |>
  addTiles() |>
  addCOG(url = "https://frodriguezsanchez.net/img/prueba.tif")
```

![](https://i.imgur.com/xmMSz0W.png)

I can visualise the layer if I use addGeotiff with `file` (not `url`) argument:
```r
leaflet() |>
  addTiles() |>
  addGeotiff(file = "/vsicurl/https://frodriguezsanchez.net/img/prueba.tif")
```
![Rplot](https://user-images.githubusercontent.com/1597843/195078985-0def79dd-41b6-4781-acaa-7894f571c859.png)

Is there any trick to make COGs work in leaflet? Thanks!

<sup>Created on 2022-10-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23)
#>  os       Ubuntu 20.04.5 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language en_GB:en
#>  collate  en_GB.UTF-8
#>  ctype    en_GB.UTF-8
#>  tz       Europe/Madrid
#>  date     2022-10-11
#>  pandoc   2.19.2 @ /usr/lib/rstudio/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  assertthat    0.2.1      2019-03-21 [1] RSPM (R 4.1.0)
#>  base64enc     0.1-3      2015-07-28 [1] RSPM (R 4.1.0)
#>  chromote      0.1.1      2022-09-07 [1] RSPM (R 4.2.0)
#>  class         7.3-20     2022-01-16 [2] CRAN (R 4.2.1)
#>  classInt      0.4-8      2022-09-29 [1] RSPM (R 4.2.0)
#>  cli           3.4.1      2022-09-23 [1] RSPM (R 4.2.0)
#>  codetools     0.2-18     2020-11-04 [2] CRAN (R 4.2.1)
#>  crosstalk     1.2.0      2021-11-04 [1] RSPM (R 4.1.0)
#>  curl          4.3.3      2022-10-06 [1] RSPM (R 4.2.0)
#>  DBI           1.1.3      2022-06-18 [1] RSPM (R 4.2.0)
#>  digest        0.6.29     2021-12-01 [1] RSPM (R 4.1.0)
#>  dplyr         1.0.10     2022-09-01 [1] RSPM (R 4.2.0)
#>  e1071         1.7-11     2022-06-07 [1] RSPM (R 4.2.0)
#>  evaluate      0.17       2022-10-07 [1] CRAN (R 4.2.1)
#>  fansi         1.0.3      2022-03-24 [1] CRAN (R 4.1.2)
#>  fastmap       1.1.0      2021-01-25 [1] RSPM (R 4.1.0)
#>  fs            1.5.2      2021-12-08 [1] RSPM (R 4.1.0)
#>  generics      0.1.3      2022-07-05 [1] RSPM (R 4.2.0)
#>  glue          1.6.2      2022-02-24 [1] RSPM (R 4.1.0)
#>  highr         0.9        2021-04-16 [1] RSPM (R 4.1.0)
#>  htmltools     0.5.3      2022-07-18 [1] RSPM (R 4.2.0)
#>  htmlwidgets   1.5.4      2021-09-08 [1] RSPM (R 4.1.0)
#>  httr          1.4.4      2022-08-17 [1] RSPM (R 4.2.0)
#>  jsonlite      1.8.2      2022-10-02 [1] RSPM (R 4.2.0)
#>  KernSmooth    2.23-20    2021-05-03 [2] CRAN (R 4.2.1)
#>  knitr         1.40       2022-08-24 [1] RSPM (R 4.2.0)
#>  later         1.3.0      2021-08-18 [1] RSPM (R 4.1.0)
#>  lattice       0.20-45    2021-09-22 [2] CRAN (R 4.2.1)
#>  leafem      * 0.2.0.9011 2022-10-11 [1] Github (r-spatial/leafem@1ec57b4)
#>  leaflet     * 2.1.1      2022-03-23 [1] RSPM (R 4.2.0)
#>  lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3      2022-03-30 [1] RSPM (R 4.2.0)
#>  mime          0.12       2021-09-28 [1] RSPM (R 4.1.0)
#>  pillar        1.8.1      2022-08-19 [1] RSPM (R 4.2.0)
#>  pkgconfig     2.0.3      2019-09-22 [1] RSPM (R 4.1.0)
#>  png           0.1-7      2013-12-03 [1] RSPM (R 4.1.0)
#>  processx      3.7.0      2022-07-07 [1] RSPM (R 4.2.0)
#>  promises      1.2.0.1    2021-02-11 [1] RSPM (R 4.1.0)
#>  proxy         0.4-27     2022-06-09 [1] RSPM (R 4.2.0)
#>  ps            1.7.1      2022-06-18 [1] RSPM (R 4.2.0)
#>  purrr         0.3.5      2022-10-06 [1] RSPM (R 4.2.0)
#>  R.cache       0.16.0     2022-07-21 [1] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2      2022-06-13 [1] RSPM (R 4.2.0)
#>  R.oo          1.25.0     2022-06-12 [1] RSPM (R 4.2.0)
#>  R.utils       2.12.0     2022-06-28 [1] RSPM (R 4.2.0)
#>  R6            2.5.1      2021-08-19 [1] RSPM (R 4.1.0)
#>  raster        3.6-3      2022-09-18 [1] RSPM (R 4.2.0)
#>  Rcpp          1.0.9.4    2022-10-09 [1] local
#>  reprex        2.0.2      2022-08-17 [1] RSPM (R 4.2.0)
#>  rlang         1.0.6      2022-09-24 [1] RSPM (R 4.2.0)
#>  rmarkdown     2.17       2022-10-07 [1] CRAN (R 4.2.1)
#>  rstudioapi    0.14       2022-08-22 [1] RSPM (R 4.2.0)
#>  sessioninfo   1.2.2      2021-12-06 [1] RSPM (R 4.1.0)
#>  sf            1.0-8      2022-07-14 [1] CRAN (R 4.2.1)
#>  sp            1.5-0      2022-06-05 [1] RSPM (R 4.2.0)
#>  stringi       1.7.8      2022-07-11 [1] RSPM (R 4.2.0)
#>  stringr       1.4.1      2022-08-20 [1] RSPM (R 4.2.0)
#>  styler        1.7.0      2022-03-13 [1] RSPM (R 4.1.0)
#>  terra         1.6-17     2022-09-10 [1] CRAN (R 4.2.1)
#>  tibble        3.1.8      2022-07-22 [1] RSPM (R 4.2.0)
#>  tidyselect    1.1.2      2022-02-21 [1] RSPM (R 4.1.0)
#>  units         0.8-0      2022-02-05 [1] RSPM (R 4.2.0)
#>  utf8          1.2.2      2021-07-24 [1] RSPM (R 4.1.0)
#>  vctrs         0.4.2      2022-09-29 [1] RSPM (R 4.2.0)
#>  webshot       0.5.4      2022-09-26 [1] RSPM (R 4.2.0)
#>  webshot2      0.1.0      2022-05-18 [1] RSPM (R 4.2.0)
#>  websocket     1.4.1      2021-08-18 [1] RSPM (R 4.1.0)
#>  withr         2.5.0      2022-03-03 [1] RSPM (R 4.1.0)
#>  xfun          0.33       2022-09-12 [1] RSPM (R 4.2.0)
#>  xml2          1.3.3      2021-11-30 [1] RSPM (R 4.1.0)
#>  yaml          2.3.5      2022-02-21 [1] RSPM (R 4.1.0)
#> 
#>  [1] /home/frs/R/x86_64-pc-linux-gnu-library/4.0
#>  [2] /opt/R/4.2.1/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by intiluna** [comment]
Hello there,
I am experiencing the same issue as Pakillo. I created my COG with GDAL:

`gdal_translate -of COG MOD13Q1.A2021273.h17v04.006.2021341094723_250m_16_days_NDVI.tif MOD13Q1.A2021273.h17v04.006.2021341094723_250m_16_days_NDVI_cog.tif \
  -co COMPRESS=DEFLATE -co PREDICTOR=2 -co NUM_THREADS=ALL_CPUS \
  -a_nodata -9999`

You can access my sample COG [here](https://storage.googleapis.com/test_open_data/MOD13Q1.A2021273.h17v04.006.2021341094723_250m_16_days_NDVI_cog.tif)

I run the sample code from https://r-spatial.github.io/leafem/reference/addCOG.html:

  `library(leaflet)

   library(leafem)

   url1 = "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/46/X/DG/2022/8/S2B_46XDG_20220829_0_L2A/L2A_PVI.tif"

   url2= "https://storage.googleapis.com/test_open_data/MOD13Q1.A2021273.h17v04.006.2021341094723_250m_16_days_NDVI_cog.tif"

    leaflet() |>
    addTiles() |>
    leafem:::addCOG(
      url = url1
      , group = "COG"
      , resolution = 50
      , autozoom = TRUE
    )`


Which works fine with url1 (sample)  but not with mine COG (url2)
Thanks for any guidance,
Inti

**Comment by tim-salabim** [comment]
Hi @Pakillo & @ILunaA, when opening the resulting map in a browser and inspecting the console output, it shows a CORS error, so you need to set the CORS permissions in your storage to allow Cross-Origin Resource Sharing. See e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Pakillo** [comment]
Dear @tim-salabim 

Many thanks for looking into this. So I understand the problem is with *where* you store the COGs; it must support CORS. Alright!

I've tried with some COGs hosted in Zenodo and it works indeed, e.g.
```r
library(leaflet)
library(leafem)
leaflet() |> 
  addTiles() |> 
  addCOG(url = "https://zenodo.org/api/files/6d8c75b3-6d84-42de-87e7-f1b5d0a5f9a1/copernicus_DSM_1000m_shaded_mood_bbox_epsg3035.tif",
         resolution = 150,
         opacity = 0.5)
```

 So I'm happy to close this issue if @ILunaA also agrees

Cheers!

**Comment by tim-salabim** [comment]
Nice! There's one more little thing to note which is especially relevant if the data are large. Before `gdal_translate`ing it to COG, you would want to run `gdaladdo` to create the pyramid overviews for the different zoom levels

**Comment by intiluna** [comment]
Thank you Tim and Pakillo, your comments help me a lot. It is clear from my side. Kind regards!!
Inti

**Comment by tim-salabim** [comment]
Alright, closing the issue then. Thanks everyone
