### ISSUE TITLE
check error with _R_CHECK_FORCE_SUGGESTS_=false _R_CHECK_DEPENDS_ONLY_=true

### ISSUE THREAD

**Issue by edzer** [r-spatial/leafem#70]
When checking the package without suggested package (as CRAN now routinely does), we get
```
Running examples in ‘leafem-Ex.R’ failed
The error most likely occurred in:

> ### Name: addReactiveFeatures
> ### Title: Add a reactive layer to map.
> ### Aliases: addReactiveFeatures
> 
> ### ** Examples
> 
> library(leaflet)
> library(leafem)
> library(sf)
Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
> library(geojsonsf)
> 
> # create some random data
> che = st_as_sf(gadmCHE)
> pts = st_as_sf(st_sample(che, 200))
Error in st_segmentize.sfc(st_as_sfc(bb), units::set_units(1, "degree",  : 
  package lwgeom required, please install it first
Calls: st_as_sf ... st_poly_sample -> st_bbox -> st_segmentize -> st_segmentize.sfc
Execution halted
* checking PDF version of manual ... OK
* DONE

Status: 1 ERROR, 1 NOTE
```
I could work on this in `sf`, but am not sure what to do-probably `st_sample` should fail anyway in this case (when working with geodetic coordinates) . The example should be conditional to lwgeom being present.

**Comment by edzer** [comment]
A patch release to CRAN would help me getting `stars` released.

**Comment by tim-salabim** [comment]
I'll try my best to release this week

**Comment by edzer** [comment]
That would be fantastic!

**Comment by edzer** [comment]
`leafem` now has `ERROR`s on CRAN: https://cran.r-project.org/web/checks/check_results_leafem.html

**Comment by tim-salabim** [comment]
Thanks for the info. I plan to take a look on Sunday. Won't have time before then

**Comment by tim-salabim** [comment]
Submitted to CRAN

**Comment by tim-salabim** [comment]
> Dear maintainer,
thanks, package leafem_0.2.3.tar.gz is on its way to CRAN.
Best regards,
CRAN teams' auto-check service
Package check result: OK
No changes to worse in reverse depends.
