### ISSUE TITLE
addCOG does not appear

### ISSUE THREAD

**Issue by bevingtona** [r-spatial/leafem#74]
Thanks for the wonderful package! 

I am able to replicate the tutorial using Sentinel data, but not with my own COG. The COG I have online seems correct as it is readable with `terra` and also with QGIS. 

Any insights would be helpful.. Thanks! 

```library(leaflet)
library(leafem)

# THIS WORKS ####

url = "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/46/X/DG/2022/8/S2B_46XDG_20220829_0_L2A/L2A_PVI.tif"
leaflet() |>
  addTiles() |>
  leafem:::addCOG(
    url = url, 
    group = "COG", 
    resolution = 1024, 
    autozoom = TRUE)

# THIS DOES NOT WORK ####
url = "https://bcsheds.sfo2.cdn.digitaloceanspaces.com/BC_2023v2-0000020480-0000043520_cog_defl.tif"
leaflet() |>
  addTiles() |>
  leafem:::addCOG(
    url = url, 
    group = "COG", 
    resolution = 1024, 
    autozoom = TRUE)

# TESTING MY COG WITH TERRA, THIS WORKS #
library(terra)
r <- rast(url)
r
plot(r)

**Comment by trafficonese** [comment]
That is probably a CORS problem.
In Chrome there is a plugin called "Moesif CORS", where you can deactivate CORS and then the layer appears.

Otherwise you will get this error in the browser console:
`Access to XMLHttpRequest at 'https://bcsheds.sfo2.cdn.digitaloceanspaces.com/BC_2023v2-0000020480-0000043520_cog_defl.tif.ovr' from origin 'http://localhost:15764' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by tim-salabim** [comment]
You need to enable CORS

Here's the error message from the browser console:

"Access to XMLHttpRequest at 'https://bcsheds.sfo2.cdn.digitaloceanspaces.com/BC_2023v2-0000020480-0000043520_cog_defl.tif.ovr' from origin 'http://localhost:15199' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by bevingtona** [comment]
Ah thanks @tim-salabim and @trafficonese ! 

I'm a bit out of my comfort zone with CORS.. I'm trying to configure to something that seems reasonable, but not sure what to put in the digitalocean CORS menu. 

![image](https://github.com/r-spatial/leafem/assets/9651129/51d28920-9c1d-4268-8bee-88ad15160720)

Strange that QGIS and `terra` can read the COG, but not leaflet..?
Ive looked throught the past issues on this topic and can't find a good example or explanation of the parameters required in the CORS.. 

For now I'd like to have my local R leafem workflow read the cog, but eventually I'd like to have that live on a shiny app... 

Thanks again!

**Comment by tim-salabim** [comment]
> Strange that QGIS and terra can read the COG, but not leaflet..?

That's probably because leaflet is a browser app and browsers are very strict with CORS...
For method I would suggest GET. This is the header I've set on AWS S3 for some example COGs (e.g. the one below)

```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "Access-Control-Allow-Origin"
        ]
    }
]
```

```r
url = "https://raster-tiles-data.s3.eu-central-1.amazonaws.com/natearth_3857_cog.tif"
leaflet() |>
  addTiles() |>
  leafem:::addCOG(
    url = url, 
    group = "COG", 
    resolution = 96, 
    autozoom = TRUE)
```

**Comment by bevingtona** [comment]
Hi @tim-salabim 

That worked! I feel like it took a few hours to kick in the new CORS policy on DigitalOcean. I changed it, then it didn't work. And I just retried and it's all good. 


```
url = "https://bcsheds.sfo2.cdn.digitaloceanspaces.com/BC_2023v2-0000020480-0000043520_cog_defl.tif"
leaflet() |>
  addTiles() |>
  leafem:::addCOG(
    url = url, 
    group = "COG", 
    resolution = 1024, 
    autozoom = TRUE)
```

Thanks so much! This opens up a whole new world of hosting imagery accessible via leaflet in r.

**Comment by tim-salabim** [comment]
Nice! Be warned though that you may find things not behaving as expected. Please open issues as you stumble across such cases. I think many of them can be resolved by updating the upstream dependency, but I rarely find time for dev work these days. So I'm usually waiting for things to break until I update things...
