### ISSUE TITLE
NA values as 255 in mouseover (imagequery) using addGeotiff

### ISSUE THREAD

**Issue by szylinski-sa** [r-spatial/leafem#96]
I'm using addGeotiff to map a masked raster:

```
leaflet() %>% 
  addProviderTiles("Esri.WorldImagery",
                   group = "Esri imagery") %>% 
  addGeotiff(file = filepath,   #path to a .tif file
             layerId = "tif")
```

Using the mouse to hover over the raster and get the pixel values is great, and here it correctly returns my 1 and 0 values in the coloured section. However as the image below shows, the value returned for NA pixels is 255. Is it possible to set the value shown to 'NA' here, or turn off the counter entirely as is the case when hovering over a non-raster area?

![image](https://github.com/user-attachments/assets/35c8cc97-ee8a-44a1-88d6-e96e47b4c46b)

There's also a transparent grid visible for this area which would be nice to be able to hide (though less of an issue than the pixel values).

**Comment by tim-salabim** [comment]
Can you share the data and the code to reproduce this?

**Comment by szylinski-sa** [comment]
[Data (single tif) zipped here.](https://github.com/user-attachments/files/17642965/clip.zip) This has been quickly clipped down in ArcGIS because the data is sensitive but roughly matches the extent shown in the image. it behaves exactly the same - 1s and 0s appear correctly but what should be NA - and are transparent cells - is showing as 255. Edit- and interrogating the file in Arc confirms that the cells outside the 0/1 area are no value.

Code used is as above - 

```
filepath <- "clip.tif"
leaflet() %>% 
  addProviderTiles("Esri.WorldImagery",
                   group = "Esri imagery") %>% 
  addGeotiff(file = filepath,  
             layerId = "tif")
```

**Comment by tim-salabim** [comment]
Ok, thanks! The reason for the 255 is that this is the `NoData` value set in the tif file. I need to think about whether it makes sense to show these as `NA` in R (it probably does).

This is the relevant part of `gdalinfo clip.tif`
![image](https://github.com/user-attachments/assets/2bd646a5-3a9b-4f06-ac51-2e1a3949cb45)

**Comment by szylinski-sa** [comment]
Thanks, had a feeling it was baked into the file somehow. Any advice or workaround for dealing with this in the meantime? E.g `terra::values` on `terra::rast(filepath)` returns NA rather than 255 but not sure if that's useful.

**Comment by tim-salabim** [comment]
This is now possible with a new argument `noData` in `imageQueryOptions()` as in:

```r
leaflet() %>% 
  addProviderTiles("Esri.WorldImagery",
                   group = "Esri imagery") %>% 
  addGeotiff(file = filepath,  
             layerId = "tif",
             imagequeryOptions = imagequeryOptions(noData = "NA"))
```
which gives

![image](https://github.com/user-attachments/assets/e4b26005-abda-4504-a3fe-cdfc5ccf46a9)

The default behaviour is still to use the data inherent `NoData Value` as reported by GDAL above.
Is this an acceptable solution for you?

**Comment by tim-salabim** [comment]
To hide the transparent grid:

```r
leaflet() %>% 
  addProviderTiles("Esri.WorldImagery",
                   group = "Esri imagery") %>% 
  addGeotiff(file = filepath,  
             layerId = "tif",
             colorOptions = colorOptions(na.color = "transparent"),
             imagequeryOptions = imagequeryOptions(
               noData = "move on, there's nothing to see here!"
             ))
```
![image](https://github.com/user-attachments/assets/5c74b94c-70ee-49af-bb63-bf64eb8f0e3a)
